---

## Title: ansible-arr/tasks/seerr.yml
## Description: Deploy Seerr in a docker container
## Author: Joseph Harry <findarato@gmail.com>
## Copyright: Joseph Harry <findarato@gmail.com>
## Date: 2026-04-28 15:43:23
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## You should have received a copy of the GNU General Public License along
## with this program; if not, write to the Free Software Foundation, Inc.
## 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


- name: Install Python tools for docker
  ansible.builtin.pip:
    name: docker==7.1.0
  tags:
    - seerr
    - arr

- name: Add seerr to Arr network
  community.docker.docker_network:
    name: "{{ arr_network_name }}"
  tags:
    - seerr
    - arr

- name: 'Create directory for container data'
  ansible.builtin.file:
    path: "{{ docker_data_dir }}/{{ dir }}"
    state: directory
    owner: docker
    group: docker
    mode: '0755'
  loop:
    - 'seerr_config'
  loop_control:
    loop_var: 'dir'
  tags:
    - seerr
    - arr

- name: Recreate seerr container
  community.docker.docker_container:
    name: "{{ seerr_app_name }}"
    image: "ghcr.io/seerr-team/seerr:{{ seerr_version }}"
    state: started
    restart_policy: unless-stopped
    recreate: true
    restart: true
    pull: true
    init: true
    volumes:
      - "{{ docker_data_dir }}/seerr_config:/config"
    dns_search_domains: "{{ dns_domains }}"
    dns_servers: "{{ dns_servers }}"
    networks_cli_compatible: false
    networks:
      - name: "{{ arr_network_name }}"
      - name: traefik_proxy
        aliases:
          - seerr
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_options }}"
    healthcheck:
      test: ["CMD", "wget", "-f --no-verbose --tries=1 --spider", "http://localhost:5055/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    env:
      TZ: "America/Chicago"
    labels:
      traefik.enable: "true"
      traefik.http.routers.seerr.rule: Host(`{{ seerr_app_name }}.{{ traefik_arr_domain }}`)
      traefik.http.routers.seerr.tls: "true"
      traefik.http.routers.seerr.entrypoints: websecure
      traefik.http.services.seerr.loadbalancer.server.port: "5055"
  tags:
    - seerr
    - arr
