---

## Title: ansible-arr/tasks/sonarr.yml
## Description: Deploy Sonarr in docker container
## Author: Joseph Harry <findarato@gmail.com>
## Copyright: Joseph Harry <findarato@gmail.com>
## Date: 2026-04-28 15:43:49
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## You should have received a copy of the GNU General Public License along
## with this program; if not, write to the Free Software Foundation, Inc.
## 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


- name: Install Python tools for docker
  ansible.builtin.pip:
    name: docker==7.1.0
  tags:
    - sonarr
    - arr

- name: Private Arr network
  community.docker.docker_network:
    name: "{{ arr_network_name }}"
    internal: true
    labels:
      arr: "true"
  tags:
    - sonarr
    - arr

- name: Create Docker paths
  ansible.builtin.file:
    path: "{{ docker_data_dir }}{{ item }}"
    state: directory
    owner: docker
    group: docker
    mode: '0755'
  with_items:
    - sonarr_config
  tags:
    - sonarr
    - arr

- name: 🛑 Stop Sonarr container
  community.docker.docker_container:
    name: sonarr
    image: "lscr.io/linuxserver/sonarr:{{ sonarr_version }}"
    state: stopped
  tags:
    - sonarr
    - arr

- name: 🔥 Remove Sonarr container
  community.docker.docker_container:
    name: sonarr
    state: absent
  tags:
    - sonarr
    - arr

# - name: 📺 Remove NFS mount TV
#   community.docker.docker_volume:
#     name: nfs-tv
#     state: absent
#     driver: local
#     recreate: options-changed
#     driver_options:
#       type: nfs
#       o: "addr=10.1.1.7,rw"
#       device: :/mnt/Dedicated/Storage/TV/
#   tags:
#     - sonarr
#     - arr

- name: 📺 Create NFS mount TV
  community.docker.docker_volume:
    name: nfs-tv
    state: present
    driver: local
    recreate: options-changed
    driver_options:
      type: "{{ vault_arr_tv_mount.type }}"
      o: "{{ vault_arr_tv_mount.opts }}"
      device: "{{ vault_arr_tv_mount.device }}"
  tags:
    - sonarr
    - arr

- name: Remove NFS mount downloads
  community.docker.docker_volume:
    name: arr-downloads
    state: absent
    driver: local
  tags:
    - sonarr
    - arr

- name: Create NFS mount downloads
  community.docker.docker_volume:
    name: arr-downloads
    state: present
    driver: local
    recreate: options-changed
    driver_options:
      type: "{{ vault_arr_downloads_mount.type }}"
      o: "{{ vault_arr_downloads_mount.opts }}"
      device: "{{ vault_arr_downloads_mount.device }}"
  tags:
    - sonarr
    - arr

- name: Recreate Sonarr container
  community.docker.docker_container:
    name: "{{ sonarr_app_name }}"
    image: "lscr.io/linuxserver/sonarr:{{ sonarr_version }}"
    state: started
    restart_policy: "{{ docker_restart_condition }}"
    recreate: true
    restart: true
    pull: true
    volumes:
      - /etc/localtime:/ect/localtime:ro
      - "arr-downloads:/downloads"
      - "nfs-tv:/tv"
      - "{{ docker_data_dir }}/sonarr_config:/config"
    labels:
      traefik.enable: "true"
      traefik.http.routers.sonarr.rule: Host(`{{ sonarr_app_name }}.{{ traefik_arr_domain }}`)
      traefik.http.routers.sonarr.tls: "true"
      traefik.http.routers.sonarr.entrypoints: websecure
      traefik.http.services.sonarr.loadbalancer.server.port: "8989"
    dns_search_domains: "{{ dns_domains }}"
    dns_servers: "{{ dns_servers }}"
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_options }}"
    networks_cli_compatible: false
    networks:
      - name: "{{ arr_network_name }}"
        aliases:
          - sonarr.mcharryville.space
          - sonarr.arr.mcharryville.space
          - sonarr
      - name: traefik_proxy
        aliases:
          - sonarr.mcharryville.space
    env:
      TZ: "America/Chicago"
      PUID: '1000'
      PGID: '1000'
      VERSION: latest
  tags:
    - sonarr
    - arr
