---

## Title: ansible-arr/tasks/radarr.yml
## Description: Deploy radarr
## Author: Joseph Harry <findarato@gmail.com>
## Copyright: Joseph Harry <findarato@gmail.com>
## Date: 2026-04-28 15:39:21
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## You should have received a copy of the GNU General Public License along
## with this program; if not, write to the Free Software Foundation, Inc.
## 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


# https://github.com/leandrobattochio/trackarr

- name: Install Python tools for docker
  ansible.builtin.pip:
    name: docker==7.1.0
  tags:
    - radarr
    - arr

- name: Private Arr network
  community.docker.docker_network:
    name: "{{ arr_network_name }}"
    internal: true
    labels:
      arr: "true"
  tags:
    - radarr
    - arr

- name: Create Docker paths
  ansible.builtin.file:
    path: "{{ docker_data_dir }}/{{ item }}"
    state: directory
    owner: docker
    group: docker
    mode: '0755'
  with_items:
    - trackarr_data
    - trackarr_data/db
  tags:
    - trackarr
    - arr


- name: Recreate trackarr-db container
  community.docker.docker_container:
    name: trackarr-db
    image: postgres:17-alpine
    state: absent
    restart_policy: unless-stopped
    recreate: true
    restart: true
    pull: true
    volumes:
      - /etc/localtime:/ect/localtime:ro
      - "{{ docker_data_dir }}/trackarr_data/db:/var/lib/postgresql/data"
    dns_search_domains: "{{ dns_domains }}"
    dns_servers: "{{ dns_servers }}"
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_options }}"
    networks_cli_compatible: false
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arr -d trackarr"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - name: "{{ arr_network_name }}"
        aliases:
          - trackarr-db.mcharryville.space
          - trackarr-db.arr.mcharryville.space
          - trackarr-db
    env:
      POSTGRES_DB: trackarr
      POSTGRES_USER: arr
      POSTGRES_PASSWORD: "{{ trackarr_db_password }}"
  tags:
    - trackarr
    - arr

- name: Recreate trackarr container
  community.docker.docker_container:
    name: trackarr
    image: ghcr.io/leandrobattochio/trackarr:{{ trackarr_version }}
    state: absent
    restart_policy: unless-stopped
    recreate: true
    restart: true
    pull: true
    volumes:
      - /etc/localtime:/ect/localtime:ro
      - "{{ docker_data_dir }}/trackarr_config:/config"
    dns_search_domains: "{{ dns_domains }}"
    dns_servers: "{{ dns_servers }}"
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_options }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.trackarr.rule: Host(`{{ trackarr_app_name }}.{{ traefik_arr_domain }}`)
      traefik.http.routers.trackarr.tls: "true"
      traefik.http.routers.trackarr.entrypoints: websecure
      traefik.http.services.trackarr.loadbalancer.server.port: "3000"
    networks_cli_compatible: false
    networks:
      - name: "{{ arr_network_name }}"
        aliases:
          - trackarr.mcharryville.space
          - trackarr.arr.mcharryville.space
          - trackarr
      - name: traefik_proxy
        aliases:
          - trackarr.mcharryville.space
          - trackarr
    env:
      ASPNETCORE_ENVIRONMENT: "Production"
      APP_TIMEZONE: "America/Chicago"
      ConnectionStrings__PostgresConnection: Host=trackarr-db;Port=5432;Database=trackarr;Username=arr;Password="{{ trackarr_db_password }}"
      Hangfire__Directory: /data
      Plugins__Directory: /data
      TZ: "America/Chicago"
  tags:
    - trackarr
    - arr
