---

## Title: tasks/arr/gluetun.yml
## Description: Deploy gluetun in a docker container
## Author: Joseph Harry <findarato@gmail.com>
## Copyright: Joseph Harry <findarato@gmail.com>
## Date: 2025-10-26 15:35:12
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## You should have received a copy of the GNU General Public License along
## with this program; if not, write to the Free Software Foundation, Inc.
## 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


#      ▄████  ██▓     █    ██ ▓█████▄▄▄█████▓ █    ██  ███▄    █
#     ██▒ ▀█▒▓██▒     ██  ▓██▒▓█   ▀▓  ██▒ ▓▒ ██  ▓██▒ ██ ▀█   █
#    ▒██░▄▄▄░▒██░    ▓██  ▒██░▒███  ▒ ▓██░ ▒░▓██  ▒██░▓██  ▀█ ██▒
#    ░▓█  ██▓▒██░    ▓▓█  ░██░▒▓█  ▄░ ▓██▓ ░ ▓▓█  ░██░▓██▒  ▐▌██▒
#    ░▒▓███▀▒░██████▒▒▒█████▓ ░▒████▒ ▒██▒ ░ ▒▒█████▓ ▒██░   ▓██░
#     ░▒   ▒ ░ ▒░▓  ░░▒▓▒ ▒ ▒ ░░ ▒░ ░ ▒ ░░   ░▒▓▒ ▒ ▒ ░ ▒░   ▒ ▒
#      ░   ░ ░ ░ ▒  ░░░▒░ ░ ░  ░ ░  ░   ░    ░░▒░ ░ ░ ░ ░░   ░ ▒░
#    ░ ░   ░   ░ ░    ░░░ ░ ░    ░    ░       ░░░ ░ ░    ░   ░ ░
#          ░     ░  ░   ░        ░  ░           ░              ░

# - name: Create Docker paths
#   file:
#     path: "{{ docker_gluetun_storage }}{{ item }}"
#     state: directory
#   with_items:
#     - config
#   tags:
#     - gluetun
#     - arr

- name: 🏴‍☠️ Create and Update gluetun Container
  community.docker.docker_container:
    name: gluetun
    image: "qmcgaw/gluetun:{{ docker_gluetun_vars.gluetun_release }}"
    hostname: gluetun
    state: started
    restart_policy: "{{ docker_gluetun_vars.docker_restart_condition }}"
    env:
      TZ: America/Chicago
      VPN_SERVICE_PROVIDER: mullvad
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: "{{ docker_gluetun_vars.private_key }}"
      WIREGUARD_ADDRESSES: "{{ docker_gluetun_vars.addresses }}"
      SERVER_COUNTRIES: "{{ docker_gluetun_vars.countries }}"
      SERVER_CITIES: "{{ docker_gluetun_vars.cities }}"
      HEALTH_RESTART_VPN: "on"
      HEALTH_ICMP_TARGET_IPS: "1.1.1.1,8.8.8.8"
      HEALTH_TARGET_ADDRESSES: "cloudflare.com:443,github.com:443"
    volumes:
      - /etc/localtime:/ect/localtime:ro
      - /dev/net/tun:/dev/net/tun
    # networks:
    #   - name: "{{ traefik_proxy_network }}" # Connect to traefik for routing
    #     gw_priority: 10
    labels:
      traefik.enable: "true"
      traefik.http.routers.deluge.rule: Host(`{{ deluge_app_name }}.{{ traefik_domain }}`)
      traefik.http.routers.deluge.tls: "true"
      traefik.http.routers.deluge.entrypoints: websecure
      traefik.http.services.deluge.loadbalancer.server.port: "8112"
      traefik.tcp.services.deluge-tcp.loadbalancer.server.port: "58846"
    capabilities:
      - NET_ADMIN
  tags:
    - gluetun
    - arr
    - vpn
